version: "3.8"
services:
  myflask:
    build: flask-project/
    ports:
      - 8000:8000
    env_file:
      - env/flask.env

  mynginx:
    build: nginx/
    ports:
      - 80:80
    depends_on:
      - "myflask"