apiVersion: v1
kind: Service
metadata:
  name: myflask
  labels:
    run: myflask
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    run: myflask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask
spec:
  selector:
    matchLabels:
      run: myflask
  replicas: 1
  template:
    metadata:
      labels:
        run: myflask
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: flask-secret
      # - name: flask-configmap-volume
      #   configMap:
      #     name: flask-configmap-volume
      containers:
      - name: flask
        image: redtea89/pre-flask:arm
        ports:
        - containerPort: 8000
        # volumeMounts:
        # - mountPath: /etc/flask/ssl
        #   name: secret-volume
        # - mountPath: /etc/flask/conf.d
        #   name: flask-configmap-volume