apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: my-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      volumes:
      - name: nginx-configmap-volume
        configMap:
          name: nginx-configmap-volume
      # - name: secret-volume
      #   secret:
      #     secretName: nginxsecret
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        # - mountPath: /etc/nginx/ssl
        #   name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: nginx-configmap-volume